// src/contexts/OnboardingContext.jsx
import React, { createContext, useContext, useState } from 'react';

const OnboardingContext = createContext();

export const useOnboarding = () => {
  const context = useContext(OnboardingContext);
  if (!context) {
    throw new Error('useOnboarding must be used within OnboardingProvider');
  }
  return context;
};

export const OnboardingProvider = ({ children }) => {
  const [onboardingData, setOnboardingData] = useState({
    // Step 1: Company Details
    company_name: '',
    company_email: '',
    company_phone: '',
    
    // Step 2: Team Setup (optional)
    teammate_emails: [],
    
    // Step 3: Plan Selection
    subscription_plan_code: '',
    billing_cycle: 'monthly', // 'monthly' or 'annual'
    selected_plan: null, // Full plan object with pricing
    
    // Step 4: Framework Selection
    framework_id: '',
    framework_name: '',
    selected_frameworks: [], // ✅ Array of selected frameworks
    
    // Step 5: After tenant creation (backend response)
    tenant_slug: '', // Auto-generated by backend
    tenant_status: '', // PENDING_PAYMENT, ACTIVE, etc.
    payment_amount: 0,
    payment_id: '',
  });

  const updateOnboardingData = (data) => {
    setOnboardingData((prev) => ({ ...prev, ...data }));
  };

  const resetOnboardingData = () => {
    setOnboardingData({
      company_name: '',
      company_email: '',
      company_phone: '',
      teammate_emails: [],
      subscription_plan_code: '',
      billing_cycle: 'monthly',
      selected_plan: null,
      framework_id: '',
      framework_name: '',
      selected_frameworks: [], // ✅ Added here too
      tenant_slug: '',
      tenant_status: '',
      payment_amount: 0,
      payment_id: '',
    });
  };

  return (
    <OnboardingContext.Provider
      value={{
        onboardingData,
        updateOnboardingData,
        resetOnboardingData,
      }}
    >
      {children}
    </OnboardingContext.Provider>
  );
};