// src/pages/Checkout.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useOnboarding } from '../contexts/OnboardingContext';
import { tenantAPI } from '../services/tenantService';
import './Checkout.css';

const Checkout = () => {
  const navigate = useNavigate();
  const { onboardingData } = useOnboarding();
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState(null);

  // ✅ Get from context first, fallback to sessionStorage
  const selectedPlan = onboardingData.selected_plan || 
                       JSON.parse(sessionStorage.getItem('selectedPlan') || '{}');
  
  const selectedFrameworks = JSON.parse(sessionStorage.getItem('selectedFrameworks') || '[]');

  // ✅ Validate we have required data
  useEffect(() => {
    if (!onboardingData.company_name || !selectedPlan.plan_code) {
      alert('Missing required information. Please start from the beginning.');
      navigate('/workspace-name');
    }
  }, []);

  const formatPrice = (price) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2
    }).format(price);
  };

  const calculateTotal = () => {
    return selectedPlan.price || 0;
  };

  // ✅ REAL API CALL
  const handlePayment = async () => {
    setProcessing(true);
    setError(null);

    try {
      // ============================================================================
      // STEP 1: Create tenant record with PENDING_PAYMENT status
      // ============================================================================
// ============================================================================
      // STEP 1: Create tenant record with PENDING_PAYMENT status
      // ============================================================================
      
      // ✅ Format frameworks for backend
      const requestedFrameworks = selectedFrameworks.map(framework => ({
        id: framework.id,
        name: framework.name
      }));

      const tenantData = {
        company_name: onboardingData.company_name,
        company_email: onboardingData.company_email || `admin@${onboardingData.company_name.toLowerCase().replace(/\s+/g, '')}.com`,
        subscription_plan_code: selectedPlan.plan_code,
        requested_frameworks: requestedFrameworks, // ✅ NEW: Send frameworks
        // tenant_slug will be auto-generated by backend if not provided
      };

      console.log('Creating tenant with data:', tenantData);

      const createResponse = await tenantAPI.create(tenantData);

      console.log('Tenant creation response:', createResponse);

      if (!createResponse.success) {
        throw new Error(createResponse.error || 'Failed to create tenant');
      }

      // ============================================================================
      // STEP 2: Show success message with tenant info
      // ============================================================================
      const tenantSlug = createResponse.tenant_slug;

      alert(
        `✅ Tenant Created Successfully!\n\n` +
        `Company: ${createResponse.company_name}\n` +
        `Tenant ID: ${tenantSlug}\n` +
        `Status: ${createResponse.status}\n` +
        `Plan: ${createResponse.plan}\n` +
        `Amount: $${createResponse.amount}\n\n` +
        `⏳ Payment Status: PENDING\n\n` +
        `Next Steps:\n` +
        `1. Admin will verify your payment\n` +
        `2. You'll receive an activation email\n` +
        `3. Then you can access your dashboard\n\n` +
        `Your Tenant ID: ${tenantSlug}`
      );

      // ============================================================================
      // STEP 3: Store tenant slug for later reference
      // ============================================================================
// ============================================================================
      // STEP 3: Store tenant slug for later reference
      // ============================================================================
      sessionStorage.setItem('tenant_slug', tenantSlug);
      sessionStorage.setItem('tenant_status', createResponse.status);
      
      // ✅ Keep frameworks for PendingActivation page
      sessionStorage.setItem('requested_frameworks', JSON.stringify(requestedFrameworks));

      // ============================================================================
      // STEP 4: Clear onboarding data and redirect
      // ============================================================================
      sessionStorage.removeItem('selectedPlan');
      sessionStorage.removeItem('selectedFrameworks');

      // Redirect to a "pending activation" page or login
      navigate('/pending-activation', { 
        state: { 
          tenantSlug,
          companyName: createResponse.company_name,
          planName: createResponse.plan
        } 
      });

    } catch (err) {
      console.error('Tenant creation failed:', err);
      setError(err.response?.data?.error || err.message || 'Failed to create tenant. Please try again.');
    } finally {
      setProcessing(false);
    }
  };

  return (
    <div className="checkout-page">
      <div className="checkout-content">
        <div className="checkout-grid">
          {/* Order Summary */}
          <div className="order-summary">
            <h2>Order Summary</h2>
            
            {/* Company Info */}
            <div className="summary-section">
              <h3>Company Information</h3>
              <div className="info-item">
                <span className="label">Company Name:</span>
                <span className="value">{onboardingData.company_name}</span>
              </div>
              <div className="info-item">
                <span className="label">Team Members:</span>
                <span className="value">{onboardingData.teammate_emails?.length || 0}</span>
              </div>
            </div>

            {/* Subscription Plan */}
            <div className="summary-section">
              <h3>Subscription Plan</h3>
              <div className="plan-item">
                <div className="item-details">
                  <span className="item-name">{selectedPlan.plan_name} Plan</span>
                  <span className="item-billing">
                    {selectedPlan.billing_cycle === 'monthly' ? 'Monthly' : 'Annual'} billing
                  </span>
                </div>
                <span className="item-price">{formatPrice(selectedPlan.price)}</span>
              </div>
            </div>

            {/* Selected Frameworks */}
            <div className="summary-section">
              <h3>Selected Frameworks ({selectedFrameworks.length})</h3>
              {selectedFrameworks.map(framework => (
                <div key={framework.id} className="framework-item">
                  <i className="fas fa-check-circle"></i>
                  <span>{framework.name}</span>
                </div>
              ))}
            </div>

            {/* Total */}
            <div className="summary-total">
              <span>Total Amount</span>
              <span className="total-amount">{formatPrice(calculateTotal())}</span>
            </div>
          </div>

          {/* Payment Form */}
          <div className="payment-form">
            <h2>Complete Your Order</h2>
            
            {error && (
              <div className="error-message">
                <i className="fas fa-exclamation-circle"></i>
                <p>{error}</p>
              </div>
            )}

            <div className="payment-notice">
              <i className="fas fa-info-circle"></i>
              <div>
                <p><strong>Manual Payment Verification</strong></p>
                <p>After submitting this order, an admin will verify your payment and activate your account. You'll receive an email notification once activated.</p>
              </div>
            </div>

            <button 
              className="pay-button"
              onClick={handlePayment}
              disabled={processing}
            >
              {processing ? (
                <>
                  <i className="fas fa-spinner fa-spin"></i>
                  Creating Your Account...
                </>
              ) : (
                <>
                  <i className="fas fa-check-circle"></i>
                  Submit Order - {formatPrice(calculateTotal())}
                </>
              )}
            </button>

            <div className="security-badges">
              <i className="fas fa-shield-check"></i>
              <span>Secure order processing</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Checkout;